In [2]:
import numpy as np

In [29]:
# board = np.random.randint(low=1, high=10, size=(3,3,3,3))
board = np.random.randint(low=1, high=10, size=(9,9))

# def printboard(board):
#     for bri, br in enumerate(board):
#         for bi, b in enumerate(br):
#             for ri, r in enumerate(b):
#                 for ii, item in enumerate(r):
#                     print(item, end="")
#                 print("\n")

def printboard(board):
    for ri, row in enumerate(board):
        if ri != 0: print()
        if ri in [0,3,6]:
                print("-"*13)
        for i, item in enumerate(row):
            if i in [0,3,6]:
                print("|", end="")
            print(item, end="")
            if i in [8]:
                print("|", end="")
        if ri in [8]:
                print()
                print("-"*13)
                
printboard(board)

-------------
|472|263|115|
|331|274|427|
|873|552|911|
-------------
|114|471|868|
|784|823|966|
|778|376|659|
-------------
|364|893|127|
|966|193|532|
|786|828|945|
-------------


In [32]:
def get_empty_board():
    return np.zeros(shape=(9,9), dtype=int)


board = get_empty_board()

printboard(board)

-------------
|000|000|000|
|000|000|000|
|000|000|000|
-------------
|000|000|000|
|000|000|000|
|000|000|000|
-------------
|000|000|000|
|000|000|000|
|000|000|000|
-------------


In [112]:
import random

def generate_matrix_with_nonzero_integer_determinant(n, max_coef):
    # Start with an identity matrix of size n
    matrix = [[1 if i == j else 0 for j in range(n)] for i in range(n)]

    # Perform a sequence of row operations
    for i in range(n):
        # Choose a random row to swap with row i
        j = random.randint(i, n-1)
        matrix[i], matrix[j] = matrix[j], matrix[i]

        # Choose a random scalar within the specified range and add it to row i
        scalar = random.randint(-max_coef, max_coef)
        for j in range(n):
            coef = random.randint(-max_coef, max_coef)
            matrix[i][j] += coef * scalar * matrix[i-1][j]

    # The final matrix has a non-zero integer determinant
    return matrix


import numpy as np
M = np.matrix(generate_matrix_with_nonzero_integer_determinant(3, 3))
print(np.linalg.det(M))
print(np.linalg.solve(M, np.zeros(shape=M.shape[0])))
print(M)

25.000000000000007
[ 0. -0.  0.]
[[ 4  0  1]
 [17  0 -2]
 [34  1 -4]]


In [ ]:
can you write me a code that generates a square matrix M and a vector b:
- all of the values in M and b are integers. They can be zero.
- none of the values in M is larger than 'maxval_M' which is given as input to the function
- none of the values in b is larger than 'maxval_b' which is given as input to the function
- When we write Mx=b, there is a unique solution for the vector x, where each entry in x is not larger than `maxval_x` given as input to the function, and each entry of x is a non-zero integer
    

# or b can be larger than 'maxval', 
# , with n rows and n columns that satisfies the following constraints:
# - M is given as an input to the function
# - no value of M is larger than 'maxval' which is another input to the function
# - We can write the matrix equation Mx = b, where M is the matrix, b is a vector of height n wher


# matrix A with N rows and N columns that satisfy the following constraints
# - N and M are given as input, but we ensure that N > M to ensure that the system can be solved.
# - they system should be solvable as a system of linear equations. There shoul

In [164]:
# import random
# import numpy as np

# # def generate_linear_system(maxval_M, maxval_b, maxval_x):
# #     while True:
# #         # Generate random coefficients and constants for each equation
# #         M = [[random.randint(-maxval_M, maxval_M) for j in range(maxval_x)] for i in range(maxval_x)]
# #         b = [random.randint(-maxval_b, maxval_b) for i in range(maxval_x)]

# #         # Verify that the linear system has a unique, non-zero, integer solution
# #         try:
# #             x = np.linalg.solve(M, b)
# #         except np.linalg.LinAlgError:
# #             continue

# #         if all(int(xi) == xi and xi != 0 for xi in x) and len(set(x)) == maxval_x:
# #             break

# #     return M, b

# # import numpy as np

# import random
# import numpy as np

# def generate_linear_system(n, maxval_M, maxval_b, maxval_x):
#     while True:
#         # Generate random coefficients and constants for each equation
#         M = [[random.randint(-maxval_M, maxval_M) for j in range(n)] for i in range(n)]
#         b = [random.randint(-maxval_b, maxval_b) for i in range(n)]

#         # Verify that the linear system has a unique, non-zero, integer solution
#         try:
#             x = np.linalg.solve(M, b)
#         except np.linalg.LinAlgError:
#             continue

#         if all(int(xi) == xi and xi != 0 for xi in x) and len(set(x)) == n:
#             break

#     return M, b


# # Generate a linear system
# M, b = generate_linear_system(4, 10, 2, 2)

# # Solve the linear system using numpy
# x = np.linalg.solve(M, b)

# # Print the matrix, vector, and solution
# print("Matrix M:")
# print(M)
# print("Vector b:")
# print(b)
# print("Solution vector x:")
# print(x)

# print(M@x, b)

In [200]:
import random
import numpy as np

def generate_matrix_and_vector(n, maxval_M, maxval_b, maxval_x):
    M = np.zeros((n, n), dtype=int)
    x = np.zeros((n,), dtype=int)
    b = np.zeros((n,), dtype=int)

    for i in range(n):
        x[i] = random.randint(1, maxval_x)

    for i in range(n):
        for j in range(n):
            M[i, j] = random.randint(1, maxval_M)

        # Ensure that the dot product of M and x doesn't exceed maxval_b
        while True:
            b[i] = np.dot(M[i], x)
            if b[i] <= maxval_b:
                break
            else:
                # Update the coefficients of M if the dot product exceeds maxval_b
                for j in range(n):
                    M[i, j] = random.randint(1, maxval_M)

    return M, b, x

n = 3
maxval_M = 10
maxval_b = 20
maxval_x = 4

M, b, x = generate_matrix_and_vector(n, maxval_M, maxval_b, maxval_x)

print("Matrix M:")
print(M)
print("\nVector b:")
print(b)
print("\nSolution Vector x:")
print(x)

print("Verification")
print(M.astype(float)@x.astype(float), b)



Matrix M:
[[1 1 5]
 [1 2 4]
 [1 1 7]]

Vector b:
[16 17 20]

Solution Vector x:
[3 3 2]
Verification
[16. 17. 20.] [16 17 20]


In [527]:
import random
import numpy as np

def get_random_non_zero_integer(maxval, minval):
    maxvalsafe = max(maxval, minval)
    minvalsafe = min(maxval, minval)
    if (minvalsafe > 0) or (maxvalsafe < 0):
        return random.randint(minvalsafe, maxvalsafe)
    else:
        pos = random.randint(1, maxvalsafe)
        neg = random.randint(minvalsafe, -1)
        return random.choice((pos, neg))


def generate_matrix_and_vectors(n, m, maxval_M, maxval_b, maxval_x):
    M = np.zeros((n, m), dtype=int)
    x = np.zeros((m,), dtype=int)
    b = np.zeros((n,), dtype=int)

    for i in range(m):
        x[i] = get_random_non_zero_integer(-maxval_x, maxval_x)

    for i in range(m):
        for j in range(m):
            M[i, j] = get_random_non_zero_integer(-maxval_M, maxval_M)

        # Ensure that the dot product of M and x doesn't exceed maxval_b
        while True:
            b[i] = np.dot(M[i], x)
            if b[i] <= maxval_b:
                break
            else:
                # Update the coefficients of M if the dot product exceeds maxval_b
                for j in range(m):
                    M[i, j] = get_random_non_zero_integer(-maxval_M, maxval_M)

    # add linearly dependent rows
    for i in range(m, n):
        for j in range(m):
            mult = random.choice([-1,0,1])
            M[i] += M[j]*mult
            b[i] += b[j]*mult

    # ensure the matrix has a unique solution
    # we only look at the upper square (m,m) part of the matrix as the remaining ((n-m),m) rows
    # are linearly dependent on the previous rows.
    M2 = M[:m].copy()
    M2[:,-1] -= b[:m]
    detM2 = np.linalg.det(M2)
    if np.isclose(detM2, 0):
        # determinant is zero, so probably more than 1 solution
        return generate_matrix_and_vectors(n, m, maxval_M, maxval_b, maxval_x)
    else:
        return M, x, b

n = 4  # rows
m = 2
maxval_M = 3
maxval_b = 3
maxval_x = 3  

M, x, b = generate_matrix_and_vectors(n, m, maxval_M, maxval_b, maxval_x)

print("Matrix M:")
print(M)
print("\nVector b:")
print(b)
print("\nSolution Vector x:")
print(x)
print("Alt solution x:")
sol = np.linalg.solve(M[:m], b[:m])
# sol = np.linalg.solve(M[-m:], b[-m:])
print(sol)

print("Verification")
print(M.astype(float)@x.astype(float), b)

Matrix M:
[[-3  2]
 [-1 -2]
 [-3  2]
 [-3  2]]

Vector b:
[ 1 -5  1  1]

Solution Vector x:
[1 2]
Alt solution x:
[1. 2.]
Verification
[ 1. -5.  1.  1.] [ 1 -5  1  1]


In [ ]:
import random
import numpy as np

def get_random_non_zero_integer(maxval, minval):
    maxvalsafe = max(maxval, minval)
    minvalsafe = min(maxval, minval)
    if (minvalsafe > 0) or (maxvalsafe < 0):
        return random.randint(minvalsafe, maxvalsafe)
    else:
        pos = random.randint(1, maxvalsafe)
        neg = random.randint(minvalsafe, -1)
        return random.choice((pos, neg))


def generate_matrix_and_vectors(n, m, maxval_M, maxval_b, maxval_x):
    M = np.zeros((n, m), dtype=int)
    x = np.zeros((m,), dtype=int)
    b = np.zeros((n,), dtype=int)

    for i in range(m):
        x[i] = get_random_non_zero_integer(-maxval_x, maxval_x)

    for i in range(m):
        for j in range(m):
            M[i, j] = get_random_non_zero_integer(-maxval_M, maxval_M)

        # Ensure that the dot product of M and x doesn't exceed maxval_b
        while True:
            b[i] = np.dot(M[i], x)
            if b[i] <= maxval_b:
                break
            else:
                # Update the coefficients of M if the dot product exceeds maxval_b
                for j in range(m):
                    M[i, j] = get_random_non_zero_integer(-maxval_M, maxval_M)

    # add linearly dependent rows
    for i in range(m, n):
        for j in range(m):
            mult = random.choice([-1,0,1])
            M[i] += M[j]*mult
            b[i] += b[j]*mult

    # ensure the matrix has a unique solution
    # we only look at the upper square (m,m) part of the matrix as the remaining ((n-m),m) rows
    # are linearly dependent on the previous rows.
    M2 = M[:m].copy()
    M2[:,-1] -= b[:m]
    detM2 = np.linalg.det(M2)
    if np.isclose(detM2, 0):
        # determinant is zero, so probably more than 1 solution
        return generate_matrix_and_vectors(n, m, maxval_M, maxval_b, maxval_x)
    else:
        return M, x, b

In [569]:
import numpy as np
import random

def generate_filled_grid(n):
    def is_valid_move(x, y):
        return 0 <= x < n and 0 <= y < n and grid[x][y] == 0

    def count_neighbors(x, y, shape_id):
        count = 0
        for dx, dy in [(1, 0), (-1, 0), (0, 1), (0, -1)]:
            nx, ny = x + dx, y + dy
            if 0 <= nx < n and 0 <= ny < n and grid[nx][ny] == shape_id:
                count += 1
        return count

    def dfs(x, y, shape_id):
        if not is_valid_move(x, y):
            return

        neighbors = count_neighbors(x, y, shape_id)

        if neighbors >= 2:  # Prevent more than 2 connections
            return

        grid[x][y] = shape_id
        directions = [(1, 0), (-1, 0), (0, 1), (0, -1)]
        random.shuffle(directions)

        for dx, dy in directions:
            dfs(x + dx, y + dy, shape_id)

    grid = np.zeros((n, n), dtype=int)
    shape_id = 1

    for x in range(n):
        for y in range(n):
            if grid[x][y] == 0:
                dfs(x, y, shape_id)
                shape_id += 1

    return grid

n = 4
filled_grid = generate_filled_grid(n)
print(filled_grid)


[[1 2 1 1]
 [1 1 3 1]
 [1 4 1 1]
 [1 1 1 5]]
